import { StyleSheet } from 'react-native';

export const styleSingnIn = StyleSheet.create({
  herder: {
    fontFamily: 'MontserratBold',
    fontSize: 25,
    margin: '3%',
    marginTop: '10%',
    color: '#0C81F5',
  },
  tittle: {
    color: '#00000',
    fontFamily: 'Montserrat_500Medium',
    fontSize: 20,
    marginTop: '-2%',
    margin: '2%',
    textAlign: 'center',
  },
  EmailAndPass: {
    color: '#00000',
    fontFamily: 'MontserratRegular',
    fontSize: 18,
    margin: '3%',
    marginTop: '-1%',
    fontWeight: 'bold',
  },
  styleInputBox: {
    color: '#00000',
    fontFamily: 'Montserrat_500Medium',
    borderColor: '#0C81F5',
    borderWidth: 1.5,
    fontSize: 19,
    height: 42,
    margin: '3%',
    marginTop: '-1%',
    padding: 10,
  },
  forgotPass: {
    color: '#E81413',
    fontFamily: 'Montserrat_500Medium',
    fontSize: 14,
    textAlign: 'center',
    marginTop: '1%',
  },
  buttonEnter: {
    position: 'relative',
    backgroundColor: '#0CD3F5',
    borderRadius: 20,
    paddingVertical: 16,
    width: '90%',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: '3%',
  },
  textLogin: {
    fontFamily: 'MontserratRegular',
    fontSize: 18,
    color: '#ffffff',
    fontWeight: 'bold',
    marginTop: '-1%',
  },
  buttonfirstAcess: {
    position: 'relative',
    backgroundColor: '#ffffff',
    borderColor: '#0C81F5',
    borderWidth: 2,
    borderRadius: 30,
    paddingVertical: 16,
    width: '90%',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: '3%',
  },
  textFirstAcess: {
    fontFamily: 'MontserratRegular',
    fontSize: 18,
    color: '#000',
    fontWeight: 'bold',
    marginTop: '-1%',
  },
});
